### ISSUE TITLE
Image uploads that are too large fail silently

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#434]
Client receives a 413 but this isn't displayed to the user.

**Comment by agundy** [comment]
While you are looking at #435 want to see if you can easily fix this too? Should just notify the user of their problem

**Comment by fcusano9** [comment]
This issue is still happening for me.

![uploaderror](https://user-images.githubusercontent.com/25214122/48447343-a88a0500-e769-11e8-8968-3b9f25af9457.PNG)

EDIT:
I am also not receiving a prompt or anything letting me know why the upload failed.

EDIT AGAIN:
I just noticed from the commit that "fixed" this issue that they limited the upload size to 4MB but the picture that I am trying to upload is only 1.83MB so its probably failing before it ever even hits your check.
