### ISSUE TITLE
Site is completly unusable with Javascript disabled

### ISSUE THREAD

**Issue by twizmwazin** [rcos/Observatory3#678]
As the title said, disabling client Javascript makes the site entirely unusable, loading just a blank page. Even if some functionality requires Javascript, it would be nice to allow basic functionality without it.

**Comment by aeksco** [comment]
@twizmwazin Thanks for the feedback! Unfortunately the current (and future) architecture of Observatory will not be designed to operate without client-side JavaScript. This is primarily because we would need to develop and maintain two different builds of the application with little-to-no re-usability of code in their respective repositories. Implementing this would require sweeping changes across both the client and server code with virtually no significant improvement in the overall experience of Observatory. These circumstances coupled with our _extremely_ limited development resources leave us unable to justify such a drastic change to the architecture.

That being said, we should absolutely display a `Please enable client-side JavaScript` message to ensure that users understand JavaScript must be enabled for the site to function correctly - I'll detail that requirement in a separate ticket and link it to this issue.

**Comment by twizmwazin** [comment]
> we would need to develop and maintain two different builds of the application with little-to-no re-usability of code in their respective repositories

Can you elaborate on that? I'm not understanding what would require two whole separate applications, in the long run anyways.

Thanks

**Comment by aeksco** [comment]
@twizmwazin Happy to elaborate in more detail:

In typical JavaScript-driven single-page-applications (SPAs) the server initially serves a minimally populated or blank HTML page, and the client-side JavaScript application populates that page with HTML compiled from templates that are generally (but not always) framework specific. To populate dynamic content, the client requests data from the server (usually JSON) and uses that data structure to populate the page with dynamic content. This is how Observatory currently operates. This means that the only HTML the server returns is a blank page, and all other data is fetched from the server's JSON API. The client-side JavaScript application handles everything else. This simplifies the responsibilities of the server to merely provide an authenticated JSON API, and little else. 

If we wanted Observatory to operate without client-side JavaScript, we would need the server to generate all the HTML (static and dynamic) and return the complete document each time a new page is visited. To facilitate this, we would need to re-define all of the application's templates to be compatible with the server-side rendering engine. This paradigm imposes additional performance requirements due to the fact that the server must return the entire rendered HTML document each time a page is requested, rather than just the comparatively minimal JSON data structure that describes the data rendered on the page in the JavaScript client. Additionally, all of the server's controller actions would need to be reworked significantly to accept and respond to requests from both the JavaScript and non-JavaScript client applications. Requests are currently only configured to accept `application/json` requests, whereas we would need to refactor to accept `applications/x-www-form-urlencoded` requests as well - the same would need to be done for _all_ server responses.

Despite what's been written above there are often many times where server-side rendering is an advantage, and the debate is on-going - but in 2017 even most server-side rendered applications still rely on client-side JavaScript in some capacity. Most statistics place the percentage of users who browse with JavaScript disabled to be between 0.5% and 1% - which is unfortunately too low a figure for the Observatory team to justify the development and maintenance overhead required to maintain what would essentially be two separate applications.

**Comment by aeksco** [comment]
Migrated related action item to [observatory-client #29](https://github.com/rcos/observatory-client/issues/29) - closing this ticket.
